In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report


import seaborn as sb

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.manifold import TSNE

import warnings
warnings.filterwarnings('ignore')

In [ ]:
playlistDF = pd.read_csv("cleaned_data.csv")
playlistDF.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,1gUAX2ImxDsB3YDcyxMXlB,美波,カワキヲアメク,カワキヲアメク,71,251933,False,0.541,0.846,6,-2.729,0,0.0551,0.01220,0.000149,0.1630,0.524,129.138,4,anime
1,1di1C0QI6Y92yZPYn6XYAZ,KANA-BOON,TIME,シルエット,73,240133,False,0.436,0.934,2,-2.685,1,0.0507,0.00001,0.140000,0.3210,0.384,91.481,4,anime
2,3khEEPRyBeOUabbmOPJzAG,Kenshi Yonezu,KICK BACK,KICK BACK,83,193495,False,0.577,0.941,1,-5.170,1,0.1050,0.00207,0.000003,0.0891,0.292,101.921,4,anime
3,1rN9QoVxw5U7TJkyaUR8C1,TK from Ling tosite sigure,Fantastic Magic,unravel,73,238360,False,0.508,0.889,7,-2.755,0,0.0862,0.04950,0.000000,0.0984,0.332,135.014,4,anime
4,23phSRwoMy48rwFpmuAP8q,Yoko Takahashi,残酷な天使のテーゼ/魂のルフラン,残酷な天使のテーゼ,60,247746,False,0.691,0.773,0,-5.244,0,0.0494,0.01740,0.000451,0.1170,0.502,128.162,4,anime

In [ ]:
playlistDF.shape

(10000, 20)

In [ ]:
playlistDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_id          10000 non-null  object
 1   artists           9999 non-null   object
 2   album_name        9999 non-null   object
 3   track_name        9999 non-null   object
 4   popularity        10000 non-null  int64
 5   duration_ms       10000 non-null  int64
 6   explicit          10000 non-null  bool
 7   danceability      10000 non-null  float64
 8   energy            10000 non-null  float64
 9   key               10000 non-null  int64
 10  loudness          10000 non-null  float64
 11  mode              10000 non-null  int64
 12  speechiness       10000 non-null  float64
 13  acousticness      10000 non-null  float64
 14  instrumentalness  10000 non-null  float64
 15  liveness          10000 non-null  float64
 16  valence           10000 non-null  float64
 17  tempo             10000 non-null  float64
 18  time_signature    10000 non-null  int64
 19  track_genre       10000 non-null  object
dtypes: bool(1), float64(9), int64(5), object(5)
memory usage: 1.5+ MB

In [ ]:
playlistDF.dropna(inplace=True)
playlistDF.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,1gUAX2ImxDsB3YDcyxMXlB,美波,カワキヲアメク,カワキヲアメク,71,251933,False,0.541,0.846,6,-2.729,0,0.0551,0.01220,0.000149,0.1630,0.524,129.138,4,anime
1,1di1C0QI6Y92yZPYn6XYAZ,KANA-BOON,TIME,シルエット,73,240133,False,0.436,0.934,2,-2.685,1,0.0507,0.00001,0.140000,0.3210,0.384,91.481,4,anime
2,3khEEPRyBeOUabbmOPJzAG,Kenshi Yonezu,KICK BACK,KICK BACK,83,193495,False,0.577,0.941,1,-5.170,1,0.1050,0.00207,0.000003,0.0891,0.292,101.921,4,anime
3,1rN9QoVxw5U7TJkyaUR8C1,TK from Ling tosite sigure,Fantastic Magic,unravel,73,238360,False,0.508,0.889,7,-2.755,0,0.0862,0.04950,0.000000,0.0984,0.332,135.014,4,anime
4,23phSRwoMy48rwFpmuAP8q,Yoko Takahashi,残酷な天使のテーゼ/魂のルフラン,残酷な天使のテーゼ,60,247746,False,0.691,0.773,0,-5.244,0,0.0494,0.01740,0.000451,0.1170,0.502,128.162,4,anime

In [ ]:
playlistDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9999 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_id          9999 non-null   object
 1   artists           9999 non-null   object
 2   album_name        9999 non-null   object
 3   track_name        9999 non-null   object
 4   popularity        9999 non-null   int64
 5   duration_ms       9999 non-null   int64
 6   explicit          9999 non-null   bool
 7   danceability      9999 non-null   float64
 8   energy            9999 non-null   float64
 9   key               9999 non-null   int64
 10  loudness          9999 non-null   float64
 11  mode              9999 non-null   int64
 12  speechiness       9999 non-null   float64
 13  acousticness      9999 non-null   float64
 14  instrumentalness  9999 non-null   float64
 15  liveness          9999 non-null   float64
 16  valence           9999 non-null   float64
 17  tempo             9999 non-null   float64
 18  time_signature    9999 non-null   int64
 19  track_genre       9999 non-null   object
dtypes: bool(1), float64(9), int64(5), object(5)
memory usage: 1.5+ MB

In [ ]:
playlistDF = playlistDF[['artists','track_name', 'popularity', 'track_genre', 'explicit', 'danceability']]
playlistDF.head()

,artists,track_name,popularity,track_genre,explicit,danceability
0,美波,カワキヲアメク,71,anime,False,0.541
1,KANA-BOON,シルエット,73,anime,False,0.436
2,Kenshi Yonezu,KICK BACK,83,anime,False,0.577
3,TK from Ling tosite sigure,unravel,73,anime,False,0.508
4,Yoko Takahashi,残酷な天使のテーゼ,60,anime,False,0.691

In [ ]:
playlistDF.nunique()

artists         3723
track_name      8063
popularity        98
track_genre       10
explicit           2
danceability     751
dtype: int64

In [ ]:
# apply the standard scaler to the numeric columns
playlistScaledDF = StandardScaler().fit_transform(playlistDF[["popularity", "danceability"]])
playlistScaledDF = pd.DataFrame(playlistScaledDF, columns=["popularity", "danceability"])
playlistScaledDF.head()

   popularity  danceability
0    1.135754     -0.400266
1    1.251491     -1.100851
2    1.830177     -0.160065
3    1.251491     -0.620450
4    0.499201      0.600570

In [ ]:
# one hot encode track genre column
playlistFinalDF = pd.get_dummies(playlistDF["track_genre"])
playlistFinalDF.head()

   anime  chill  emo  grunge  indian  k-pop  pop  pop-film  sad  sertanejo
0      1      0    0       0       0      0    0         0    0          0
1      1      0    0       0       0      0    0         0    0          0
2      1      0    0       0       0      0    0         0    0          0
3      1      0    0       0       0      0    0         0    0          0
4      1      0    0       0       0      0    0         0    0          0

In [ ]:
# one hot encode explicit column
explicitDF = pd.get_dummies(playlistDF["explicit"])
explicitDF.head()

   False  True
0      1      0
1      1      0
2      1      0
3      1      0
4      1      0

In [ ]:
explicitDF.columns

Index([False, True], dtype='bool')

In [ ]:
#
playlistFinalDF["track_name"] = playlistDF["track_name"]
playlistFinalDF["Not Explicit"] = explicitDF[False]
playlistFinalDF["Explicit"] = explicitDF[True]
playlistFinalDF["Popularity"] = playlistScaledDF["popularity"]
playlistFinalDF["Danceability"] = playlistScaledDF["danceability"]
playlistFinalDF.head()

,anime,chill,emo,grunge,indian,k-pop,pop,pop-film,sad,sertanejo,track_name,Not Explicit,Explicit,Popularity,Danceability
0,1,0,0,0,0,0,0,0,0,0,カワキヲアメク,1,0,1.135754,-0.400266
1,1,0,0,0,0,0,0,0,0,0,シルエット,1,0,1.251491,-1.100851
2,1,0,0,0,0,0,0,0,0,0,KICK BACK,1,0,1.830177,-0.160065
3,1,0,0,0,0,0,0,0,0,0,unravel,1,0,1.251491,-0.620450
4,1,0,0,0,0,0,0,0,0,0,残酷な天使のテーゼ,1,0,0.499201,0.600570

In [ ]:
# split the data into X data and y data
X = playlistFinalDF.copy()
X.drop("track_name", axis=1, inplace=True)
X.head()

,anime,chill,emo,grunge,indian,k-pop,pop,pop-film,sad,sertanejo,Not Explicit,Explicit,Popularity,Danceability
0,1,0,0,0,0,0,0,0,0,0,1,0,1.135754,-0.400266
1,1,0,0,0,0,0,0,0,0,0,1,0,1.251491,-1.100851
2,1,0,0,0,0,0,0,0,0,0,1,0,1.830177,-0.160065
3,1,0,0,0,0,0,0,0,0,0,1,0,1.251491,-0.620450
4,1,0,0,0,0,0,0,0,0,0,1,0,0.499201,0.600570

In [ ]:
y = playlistFinalDF['track_name'].values.reshape(-1,1)
y[:5]

array([['カワキヲアメク'],
       ['シルエット'],
       ['KICK BACK'],
       ['unravel'],
       ['残酷な天使のテーゼ']], dtype=object)

In [ ]:
# split the data into training and testing data
x_train, x_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:
# make the instance of the standard scaler
scaler = StandardScaler()

In [ ]:
# fit the scaler onto the data
X_scaler = scaler.fit(x_train)

In [ ]:
# scale the x train and test using the transform function
xTrainScaled = X_scaler.transform(x_train)
xTestScaled = X_scaler.transform(x_test)

In [ ]:
# use the sklearn tree module to make the tree classifier
from sklearn import tree

In [ ]:
# use .DecisionTreeClassifier from the tree module to make the tree classifier
treeModel = tree.DecisionTreeClassifier()

In [ ]:
# fit the model onto our scaled X training data and the trained y data
treeModel = treeModel.fit(xTrainScaled, y_train)

ValueError: ignored

In [ ]:
# make the prediction using the testing data
predictedValues = treeModel.predict(xTestScaled)